Use SafeGuard
SELECT 
SAFE_GUARD_DIR.SGD_name as 'Machine name', 
IVT_MACHINES.IMA_ENCRYPTED_DRIVES as 'Drive encrypted',
IVT_MACHINES.IMA_UNENCRYPTED_DRIVES as 'Drive not encrypted',
IVT_MACHINES.IMA_LAST_POLICY_RECEIVED as 'Last policy received on'

FROM IVT_MACHINES INNER JOIN
SAFE_GUARD_DIR ON IVT_MACHINES.IMA_MACHINE_ID = SAFE_GUARD_DIR.SGD_ID
WHERE (IVT_MACHINES.IMA_ENCRYPTED_DRIVES IS NOT NULL)
